services:
  app-frontend:
    build:
      context: src/frontend
      network: host
      args:
        VITE_PORT:
        VITE_DOMAIN:
        VITE_PROTOCOL:

    volumes:
      - nginx-html:/app/dist

    network_mode: "host"

    env_file:
      - .env

  app-backend:
    build:
      context: src/backend
      network: host

    volumes:
      - cert-dir:/var/www/certs:ro
      - files-dir:/tmp

    network_mode: "host"

    env_file:
      - .env

  app-server:
    build:
      context: src/server
      network: host

    volumes:
      - cert-dir:/var/www/certs:ro
      - nginx-html:/usr/share/nginx/html
      - ./src/server/nginx.conf:/etc/nginx/conf.d/franchise-fuji.conf:ro

    network_mode: "host"

volumes:
  nginx-html:
  cert-dir:
    external: true
  files-dir:
    external: true
