services:
  app-frontend:
    build: src/frontend

    volumes:
      - cert-key:/var/www/certs/cert.key:ro
      - cert:/var/www/certs/cert.crt:ro
      - nginx-html:/app/dist

    network_mode: "host"

    env_file:
      - .env

  app-backend:
    build: src/backend/

    volumes:
      - cert-key:/var/www/certs/cert.key:ro
      - cert:/var/www/certs/cert.crt:ro
      - files-dir:/tmp

    network_mode: "host"

    env_file:
      - .env

  app-server:
    build: src/server

    volumes:
      - nginx-html:/usr/share/nginx/html

    network_mode: "host"

volumes:
  nginx-html:
  cert-key:
    external: true
  cert:
    external: true
  files-dir:
    external: true
