services:
  crm:
    container_name: bot-crm
    build:
      context: services/crm
      network: host
      args:
        VITE_PORT:
        VITE_DOMAIN:
        VITE_PROTOCOL:


    volumes:
      - nginx-html:/app/dist

    network_mode: "host"

    env_file:
      - .env

  core:
    container_name: bot-core
    build:
      context: services/core
      network: host

    volumes:
      - cert-dir:/var/www/certs:ro
      - files-dir:/tmp
      - ./services/core:/app

    network_mode: "host"

    env_file:
      - .env

  server:
    container_name: bot-server
    build:
      context: services/server
      network: host

    volumes:
      - cert-dir:/var/www/certs:ro
      - nginx-html:/usr/share/nginx/html
      - ./services/server/nginx.conf:/etc/nginx/conf.d/default.conf

    network_mode: "host"

volumes:
  nginx-html:
  cert-dir:
    external: true
  files-dir:
    external: true
