"""Adding bid scopes

Revision ID: ce432ef44a5c
Revises: b909e8fc708f
Create Date: 2024-08-12 18:04:14.778523

"""

from typing import Sequence, Union

import db.alembic.enum as c_enum


old_options = (
    "admin",
    "crm_bid",
    "crm_budget",
    "crm_expenditure",
    "bot_bid_create",
    "bot_bid_kru",
    "bot_bid_owner",
    "bot_bid_teller_cash",
    "bot_bid_teller_card",
    "bot_bid_accountant_cash",
    "bot_bid_accountant_card",
    "bot_rate",
    "bot_worker_bid",
    "bot_technical_request_worker",
    "bot_technical_request_repairman",
    "bot_technical_request_chief_technician",
    "bot_technical_request_territorial_manager",
)
new_options = sorted(
    old_options
    + (
        "crm_fac_bid",
        "crm_cc_bid",
        "crm_cc_supervisor_bid",
    )
)

table_columns = {"post_scopes": ["scope"]}


# revision identifiers, used by Alembic.
revision: str = "ce432ef44a5c"
down_revision: Union[str, None] = "b909e8fc708f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    c_enum.update_enum(old_options, new_options, "fujiscope", table_columns)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    c_enum.update_enum(new_options, old_options, "fujiscope", table_columns)
    # ### end Alembic commands ###
