"""add workers passports and children tables and few fields in workers

Revision ID: 1a089c1691f5
Revises: 05034881b2b5
Create Date: 2024-12-22 14:55:59.413949

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_storages
from app.infra.config import settings

# revision identifiers, used by Alembic.
revision: str = "1a089c1691f5"
down_revision: Union[str, None] = "05034881b2b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "worker_children",
        sa.Column("worker_id", sa.Integer(), nullable=False),
        sa.Column("born_date", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["worker_id"], ["workers.id"], name="worker_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "workers_passports",
        sa.Column("worker_id", sa.Integer(), nullable=False),
        sa.Column(
            "document",
            fastapi_storages.integrations.sqlalchemy.FileType(settings.storage),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["worker_id"], ["workers.id"], name="worker_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("workers", sa.Column("snils", sa.String(), nullable=True))
    op.add_column("workers", sa.Column("inn", sa.String(), nullable=True))
    op.add_column("workers", sa.Column("registration", sa.String(), nullable=True))
    op.add_column("workers", sa.Column("actual_residence", sa.String(), nullable=True))
    op.add_column("workers", sa.Column("children", sa.Boolean(), nullable=True))
    op.add_column("workers", sa.Column("military_ticket", sa.String(), nullable=True))
    op.execute("UPDATE workers SET children = false")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workers", "military_ticket")
    op.drop_column("workers", "children")
    op.drop_column("workers", "actual_residence")
    op.drop_column("workers", "registration")
    op.drop_column("workers", "inn")
    op.drop_column("workers", "snils")
    op.drop_table("workers_passports")
    op.drop_table("worker_children")
    # ### end Alembic commands ###
