"""add new table for documents requests in worker bids

Revision ID: 242dff4d09c0
Revises: b042b33c49b4
Create Date: 2025-01-28 01:44:03.011812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '242dff4d09c0'
down_revision: Union[str, None] = 'b042b33c49b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_bid_documents_requests',
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('worker_bid_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['workers.id'], ),
    sa.ForeignKeyConstraint(['worker_bid_id'], ['worker_bids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worker_bid_documents_requests')
    # ### end Alembic commands ###
