"""Add view state. New states of worker bids

Revision ID: 28b8ee36521a
Revises: 242dff4d09c0
Create Date: 2025-02-03 16:35:34.850200

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = "28b8ee36521a"
down_revision: Union[str, None] = "242dff4d09c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    enum = ENUM(
        "viewed",
        "pending",
        "pending_approval",
        name="viewstatus",
    )
    enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "worker_bids",
        sa.Column(
            "view_state",
            enum,
            nullable=True,
        ),
    )
    op.add_column(
        "worker_bids",
        sa.Column(
            "iiko_service_state",
            ENUM(
                "pending",
                "approved",
                "denied",
                "pending_approval",
                "skipped",
                "not_relevant",
                name="approvalstatus",
                create_type=False,
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "worker_bids",
        sa.Column("accounting_service_comment", sa.String(), nullable=True),
    )
    op.add_column(
        "worker_bids", sa.Column("iiko_service_comment", sa.String(), nullable=True)
    )
    op.execute(
        "UPDATE worker_bids SET view_state = 'pending_approval' WHERE state = 'pending_approval'"
    )
    op.execute(
        "UPDATE worker_bids SET iiko_service_state = 'pending' WHERE state = 'pending_approval'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("worker_bids", "iiko_service_comment")
    op.drop_column("worker_bids", "accounting_service_comment")
    op.drop_column("worker_bids", "iiko_service_state")
    op.drop_column("worker_bids", "view_state")
    op.execute("DROP TYPE viewstatus")

    # ### end Alembic commands ###
