"""add columns in worker_bids

Revision ID: 532c9a04a904
Revises: 7373aeb0e65f
Create Date: 2024-12-18 20:49:11.030514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '532c9a04a904'
down_revision: Union[str, None] = '7373aeb0e65f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker_bids', sa.Column('birth_date', sa.DateTime(), nullable=True))
    op.add_column('worker_bids', sa.Column('phone_number', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker_bids', 'phone_number')
    op.drop_column('worker_bids', 'birth_date')
    # ### end Alembic commands ###
