"""New columns in tech_requests. New scope

Revision ID: 5ce7a56ae4a7
Revises: f6ce218627c2
Create Date: 2025-02-06 12:51:00.257395

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.infra.database.alembic.enum import update_enum


# revision identifiers, used by Alembic.
revision: str = "5ce7a56ae4a7"
down_revision: Union[str, None] = "f6ce218627c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


old_options = (
    "admin",
    "crm_bid",
    "crm_budget",
    "crm_expenditure",
    "crm_fac_cc_bid",
    "crm_paralegal_bid",
    "crm_my_bid",
    "crm_archive_bid",
    "crm_my_file",
    "crm_bid_readonly",
    "crm_worktime",
    "crm_accountant_card_bid",
    "bot_bid_create",
    "bot_bid_kru",
    "bot_bid_owner",
    "bot_bid_teller_cash",
    "bot_bid_teller_card",
    "bot_bid_accountant_cash",
    "bot_bid_accountant_card",
    "bot_rate",
    "bot_worker_bid",
    "bot_technical_request_worker",
    "bot_technical_request_repairman",
    "bot_technical_request_chief_technician",
    "bot_technical_request_appraiser",
    "bot_technical_request_extensive_director",
    "bot_bid_it_worker",
    "bot_bid_it_repairman",
    "bot_bid_it_tm",
    "bot_personal_cabinet",
    "bot_incident_monitoring",
    "bot_bid_fac_cc",
    "bot_subordinates_menu",
    "bot_worker_bid_security_coordinate",
    "bot_worker_bid_accounting_coordinate",
)
new_options = sorted(old_options + ("bot_technical_request_department_director",))
table_columns = {"post_scopes": ["scope"]}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "technical_requests",
        sa.Column("not_relevant_description", sa.String(), nullable=True),
    )
    op.add_column(
        "technical_requests",
        sa.Column("not_relevant_date", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "technical_requests",
        sa.Column("not_relevant_confirmation_date", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "technical_requests",
        sa.Column("not_relevant_confirmation_description", sa.String(), nullable=True),
    )
    update_enum(old_options, new_options, "fujiscope", table_columns)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("technical_requests", "not_relevant_confirmation_date")
    op.drop_column("technical_requests", "not_relevant_date")
    op.drop_column("technical_requests", "not_relevant_description")
    op.drop_column("technical_requests", "not_relevant_confirmation_description")

    update_enum(new_options, old_options, "fujiscope", table_columns)

    # ### end Alembic commands ###
