"""rename worker passport table, rename passport in worker into documents

Revision ID: 7e9dbb5c710e
Revises: 05034881b2b5
Create Date: 2025-01-22 12:13:22.315339

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "7e9dbb5c710e"
down_revision: Union[str, None] = "05034881b2b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("workers_passports", new_table_name="workers_documents")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("workers_documents", new_table_name="workers_passports")
    # ### end Alembic commands ###
