"""add fields in worker

Revision ID: 980c0a2074a2
Revises: 65267cafab6a
Create Date: 2024-12-26 16:11:28.513956

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "980c0a2074a2"
down_revision: Union[str, None] = "65267cafab6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workers", sa.Column("official_employment_date", sa.Date(), nullable=True)
    )
    op.add_column(
        "workers", sa.Column("official_dismissal_date", sa.Date(), nullable=True)
    )
    op.add_column("workers", sa.Column("patent", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workers", "patent")
    op.drop_column("workers", "official_dismissal_date")
    op.drop_column("workers", "official_employment_date")
    # ### end Alembic commands ###
