"""add new field in worker and worker bid tables

Revision ID: b042b33c49b4
Revises: 7e9dbb5c710e
Create Date: 2025-01-27 22:38:53.977487

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b042b33c49b4"
down_revision: Union[str, None] = "7e9dbb5c710e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "worker_bids", sa.Column("official_work", sa.Boolean(), nullable=True)
    )
    op.add_column("workers", sa.Column("official_work", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workers", "official_work")
    op.drop_column("worker_bids", "official_work")
    # ### end Alembic commands ###
