"""Fixing company id

Revision ID: b30db682a17a
Revises: 76586c886d0d
Create Date: 2024-05-06 16:42:10.469394

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b30db682a17a"
down_revision: Union[str, None] = "76586c886d0d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("workers", "company_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "work_times", "company_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("workers", "company_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "work_times", "company_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
