"""Add restaurant_manager in department, rename territorial manager into appraiser in technical request

Revision ID: d4f431dbac29
Revises: 05034881b2b5
Create Date: 2025-01-21 13:24:08.979280

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.infra.database.alembic.enum as c_enum


# revision identifiers, used by Alembic.
revision: str = "d4f431dbac29"
down_revision: Union[str, None] = "05034881b2b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "departments", sa.Column("restaurant_manager_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        "departments_restaurant_manager_id_fkey",
        "departments",
        "workers",
        ["restaurant_manager_id"],
        ["id"],
    )
    op.drop_constraint(
        "technical_requests_territorial_manager_id_fkey",
        "technical_requests",
        type_="foreignkey",
    )

    op.alter_column(
        "technical_requests",
        "territorial_manager_id",
        nullable=False,
        new_column_name="appraiser_id",
    )

    op.create_foreign_key(
        "technical_requests_appraiser_id_fkey",
        "technical_requests",
        "workers",
        ["appraiser_id"],
        ["id"],
    )
    c_enum.rename_enum(
        old_name="bot_technical_request_territorial_manager",
        new_name="bot_technical_request_appraiser",
        enum_name="fujiscope",
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "technical_requests",
        "appraiser_id",
        nullable=False,
        new_column_name="territorial_manager_id",
    )
    op.drop_constraint(
        "technical_requests_appraiser_id_fkey",
        "technical_requests",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "technical_requests_territorial_manager_id_fkey",
        "technical_requests",
        "workers",
        ["territorial_manager_id"],
        ["id"],
    )
    op.drop_constraint(
        "departments_restaurant_manager_id_fkey",
        "departments",
        type_="foreignkey",
    )
    op.drop_column("departments", "restaurant_manager_id")
    c_enum.rename_enum(
        old_name="bot_technical_request_appraiser",
        new_name="bot_technical_request_territorial_manager",
        enum_name="fujiscope",
    )
    ### end Alembic commands ###
