"""Add documents

Revision ID: f83b631c4ebd
Revises: b30db682a17a
Create Date: 2024-05-19 21:20:56.029581

"""

from typing import Sequence, Union

from alembic import op
import fastapi_storages
import sqlalchemy as sa

from app.infra.config import settings

# revision identifiers, used by Alembic.
revision: str = "f83b631c4ebd"
down_revision: Union[str, None] = "b30db682a17a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bids",
        sa.Column(
            "document1",
            fastapi_storages.integrations.sqlalchemy.FileType(storage=settings.storage),
            nullable=True,
        ),
    )
    op.add_column(
        "bids",
        sa.Column(
            "document2",
            fastapi_storages.integrations.sqlalchemy.FileType(storage=settings.storage),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bids", "document2")
    op.drop_column("bids", "document1")
    # ### end Alembic commands ###
