"""Add passport str in worker

Revision ID: f8875a2f4074
Revises: 28b8ee36521a
Create Date: 2025-02-06 15:11:45.498064

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f8875a2f4074"
down_revision: Union[str, None] = "28b8ee36521a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workers", sa.Column("passport_str", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workers", "passport_str")
    # ### end Alembic commands ###
