"""Adding budget record table

Revision ID: 16c0d76094d9
Revises: 8061c8c2ee33
Create Date: 2024-07-23 20:12:40.711354

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "16c0d76094d9"
down_revision: Union[str, None] = "8061c8c2ee33"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "budget_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("expenditure_id", sa.Integer(), nullable=False),
        sa.Column("limit", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["expenditure_id"],
            ["expenditures.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("budget_records")
    # ### end Alembic commands ###
