"""Removed extra column

Revision ID: 2a657d82bfc9
Revises: 6a9833617174
Create Date: 2024-08-24 21:47:07.951017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a657d82bfc9'
down_revision: Union[str, None] = '6a9833617174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('problems_it_repairman_id_fkey', 'problems_it', type_='foreignkey')
    op.drop_column('problems_it', 'repairman_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems_it', sa.Column('repairman_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('problems_it_repairman_id_fkey', 'problems_it', 'workers', ['repairman_id'], ['id'])
    # ### end Alembic commands ###
