"""create subordinations table

Revision ID: 4749aedb1134
Revises: 184806c7f82c
Create Date: 2024-09-26 12:43:29.013546

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4749aedb1134"
down_revision: Union[str, None] = "184806c7f82c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subordinations",
        sa.Column("chief_id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chief_id"],
            ["workers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["workers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("employee_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subordinations")
    # ### end Alembic commands ###
