"""create subordinations table and add scope bot_personal_cabinet

Revision ID: 4749aedb1134
Revises: 184806c7f82c
Create Date: 2024-09-26 12:43:29.013546

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import alembic_custom.enum as c_enum

old_options = (
    "admin",
    "crm_bid",
    "crm_budget",
    "crm_expenditure",
    "bot_bid_create",
    "bot_bid_kru",
    "bot_bid_owner",
    "bot_bid_teller_cash",
    "bot_bid_teller_card",
    "bot_bid_accountant_cash",
    "bot_bid_accountant_card",
    "bot_rate",
    "bot_worker_bid",
    "bot_technical_request_worker",
    "bot_technical_request_repairman",
    "bot_technical_request_chief_technician",
    "bot_technical_request_territorial_manager",
    "bot_technical_request_department_director",
    "crm_fac_bid",
    "crm_cc_bid",
    "crm_cc_supervisor_bid",
    "bot_bid_it_worker",
    "bot_bid_it_repairman",
    "bot_bid_it_tm",
)

new_options = sorted(old_options + ("bot_personal_cabinet",))
table_columns = {"post_scopes": ["scope"]}


# revision identifiers, used by Alembic.
revision: str = "4749aedb1134"
down_revision: Union[str, None] = "184806c7f82c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subordinations",
        sa.Column("chief_id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chief_id"],
            ["workers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["workers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("employee_id"),
    )
    c_enum.update_enum(old_options, new_options, "fujiscope", table_columns)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    c_enum.update_enum(new_options, old_options, "fujiscope", table_columns)
    op.drop_table("subordinations")
    # ### end Alembic commands ###
