"""create account_logins table

Revision ID: 8fe9af57052e
Revises: aaa237c15607
Create Date: 2024-09-23 21:40:19.082199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fe9af57052e'
down_revision: Union[str, None] = 'aaa237c15607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_logins',
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('cop_mail_login', sa.String(), nullable=True),
    sa.Column('liko_login', sa.String(), nullable=True),
    sa.Column('bitrix_login', sa.String(), nullable=True),
    sa.Column('pyrus_login', sa.String(), nullable=True),
    sa.Column('check_office_login', sa.String(), nullable=True),
    sa.Column('pbi_login', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_logins')
    # ### end Alembic commands ###
