"""Added sender to worker bid

Revision ID: f4080e95433c
Revises: d612fccc6fa2
Create Date: 2024-06-04 13:28:39.018026

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f4080e95433c"
down_revision: Union[str, None] = "d612fccc6fa2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("worker_bids", sa.Column("sender_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "worker_bids", "workers", ["sender_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "worker_bids", type_="foreignkey")
    op.drop_column("worker_bids", "sender_id")
    # ### end Alembic commands ###
