"""Added close date

Revision ID: ca6a57580faf
Revises: f83b631c4ebd
Create Date: 2024-05-22 09:26:23.330183

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ca6a57580faf"
down_revision: Union[str, None] = "f83b631c4ebd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bids", sa.Column("close_date", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bids", "close_date")
    # ### end Alembic commands ###
