"""Fixing nullable

Revision ID: 15c9a1a0e8eb
Revises: 76586c886d0d
Create Date: 2024-05-06 16:14:34.529854

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "15c9a1a0e8eb"
down_revision: Union[str, None] = "76586c886d0d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "work_times", "company_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "work_times", "company_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
