"""Adding denying reason to bid

Revision ID: 1dc263145dc4
Revises: 7bc3c9953c5a
Create Date: 2024-05-23 22:54:47.299789

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "1dc263145dc4"
down_revision: Union[str, None] = "7bc3c9953c5a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bids", sa.Column("denying_reason", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bids", "denying_reason")
    # ### end Alembic commands ###
