"""Add tables and columns for tech requests

Revision ID: 2ec60ce8c1ae
Revises: 319521792a8b
Create Date: 2024-08-07 13:26:13.167309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ec60ce8c1ae'
down_revision: Union[str, None] = '319521792a8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('chief_technician_id', sa.Integer(), nullable=True))
    op.add_column('departments', sa.Column('technician_id', sa.Integer(), nullable=True))
    op.add_column('departments', sa.Column('electrician_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'departments', 'workers', ['technician_id'], ['id'])
    op.create_foreign_key(None, 'departments', 'workers', ['electrician_id'], ['id'])
    op.create_foreign_key(None, 'departments', 'workers', ['chief_technician_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_column('departments', 'electrician_id')
    op.drop_column('departments', 'technician_id')
    op.drop_column('departments', 'chief_technician_id')
    # ### end Alembic commands ###
