"""Adding post_scopes table

Revision ID: 319521792a8b
Revises: 82e687e944ee
Create Date: 2024-08-05 17:49:49.645532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '319521792a8b'
down_revision: Union[str, None] = '82e687e944ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_scopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.Enum('admin', 'crm_bid', 'crm_budget', 'crm_expenditure', 'bot_bid_create', 'bot_bid_kru', 'bot_bid_owner', 'bot_bid_teller_cash', 'bot_bid_teller_card', 'bot_bid_accountant_cash', 'bot_bid_accountant_card', name='fujiscope'), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_scopes')
    # ### end Alembic commands ###
