"""Adding new field to worker

Revision ID: 5d2ec93c1975
Revises: 69ad4dc0430c
Create Date: 2024-06-11 22:17:49.531648

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5d2ec93c1975"
down_revision: Union[str, None] = "69ad4dc0430c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workers",
        sa.Column("gender", sa.Enum("man", "woman", name="gender"), nullable=True),
    )
    op.add_column("workers", sa.Column("employment_date", sa.Date(), nullable=True))
    op.add_column("workers", sa.Column("dismissal_date", sa.Date(), nullable=True))
    op.add_column(
        "workers",
        sa.Column("medical_records_availability", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workers", "medical_records_availability")
    op.drop_column("workers", "dismissal_date")
    op.drop_column("workers", "employment_date")
    op.drop_column("workers", "gender")
    # ### end Alembic commands ###
