"""Adding comment to worker bid

Revision ID: 69ad4dc0430c
Revises: d935c7d7fc20
Create Date: 2024-06-11 21:49:27.944358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69ad4dc0430c'
down_revision: Union[str, None] = 'd935c7d7fc20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker_bids', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker_bids', 'comment')
    # ### end Alembic commands ###
