"""Adding citizenship to worker

Revision ID: 73d6758fa54a
Revises: 2c8712e9cfe0
Create Date: 2024-06-19 02:58:52.158693

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "73d6758fa54a"
down_revision: Union[str, None] = "2c8712e9cfe0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workers", sa.Column("citizenship", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workers", "citizenship")
    # ### end Alembic commands ###
