"""Delete limit from expanditure

Revision ID: 8061c8c2ee33
Revises: 8d54a3097b8a
Create Date: 2024-07-23 16:19:58.311547

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8061c8c2ee33"
down_revision: Union[str, None] = "8d54a3097b8a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("expenditures", "limit")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "expenditures",
        sa.Column(
            "limit",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
