"""empty message

Revision ID: 8d54a3097b8a
Revises: 73d6758fa54a
Create Date: 2024-07-18 21:39:41.210558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d54a3097b8a'
down_revision: Union[str, None] = '73d6758fa54a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenditures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('chapter', sa.String(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('fac_id', sa.Integer(), nullable=False),
    sa.Column('cc_id', sa.Integer(), nullable=False),
    sa.Column('cc_supervisor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cc_id'], ['workers.id'], ),
    sa.ForeignKeyConstraint(['cc_supervisor_id'], ['workers.id'], ),
    sa.ForeignKeyConstraint(['fac_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expenditures')
    # ### end Alembic commands ###
