"""Added rating and fine

Revision ID: 93aa0ebd1bb4
Revises: 1bd1c05fe4df
Create Date: 2024-05-05 18:00:01.437297

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "93aa0ebd1bb4"
down_revision: Union[str, None] = "1bd1c05fe4df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("work_times", sa.Column("rating", sa.Integer(), nullable=True))
    op.add_column("work_times", sa.Column("fine", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("work_times", "fine")
    op.drop_column("work_times", "rating")
    # ### end Alembic commands ###
