"""Create group table and column in workers

Revision ID: b194833559b0
Revises: 1e063506382c
Create Date: 2024-08-20 16:46:16.075390

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b194833559b0"
down_revision: Union[str, None] = "1e063506382c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.add_column("workers", sa.Column("group_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "workers", "groups", ["group_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workers", "group_id")
    op.drop_table("groups")
    # ### end Alembic commands ###
