"""Add tables and columns for tech requests

Revision ID: b909e8fc708f
Revises: 319521792a8b
Create Date: 2024-08-11 20:54:01.130867

"""

from typing import Sequence, Union

from alembic import op
import fastapi_storages
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b909e8fc708f"
down_revision: Union[str, None] = "319521792a8b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "technical_problems",
        sa.Column(
            "executor",
            sa.Enum("technician", "chief_technician", "electrician", name="executor"),
            nullable=False,
        ),
        sa.Column("sla", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("problem_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("problem_name"),
    )
    op.create_table(
        "technical_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("problem_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "pending",
                "approved",
                "denied",
                "pending_approval",
                "skipped",
                name="approvalstatus",
            ),
            nullable=False,
        ),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("open_date", sa.DateTime(), nullable=False),
        sa.Column("deadline_date", sa.DateTime(), nullable=False),
        sa.Column("repair_date", sa.DateTime(), nullable=True),
        sa.Column("confirmation_date", sa.DateTime(), nullable=True),
        sa.Column("confirmation_description", sa.String(), nullable=True),
        sa.Column("reopen_date", sa.DateTime(), nullable=True),
        sa.Column("reopen_deadline_date", sa.DateTime(), nullable=True),
        sa.Column("reopen_repair_date", sa.DateTime(), nullable=True),
        sa.Column("reopen_confirmation_date", sa.DateTime(), nullable=True),
        sa.Column("close_date", sa.DateTime(), nullable=True),
        sa.Column("close_description", sa.String(), nullable=True),
        sa.Column("worker_id", sa.Integer(), nullable=False),
        sa.Column("repairman_id", sa.Integer(), nullable=False),
        sa.Column("territorial_manager_id", sa.Integer(), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["problem_id"],
            ["technical_problems.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repairman_id"],
            ["workers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["territorial_manager_id"],
            ["workers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["worker_id"],
            ["workers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "technical_requests_problem_photos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "document",
            fastapi_storages.integrations.sqlalchemy.FileType(),
            nullable=False,
        ),
        sa.Column("technical_request_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["technical_request_id"],
            ["technical_requests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "technical_requests_repair_photos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "document",
            fastapi_storages.integrations.sqlalchemy.FileType(),
            nullable=False,
        ),
        sa.Column("technical_request_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["technical_request_id"],
            ["technical_requests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("technical_requests_repair_photos")
    op.drop_table("technical_requests_problem_photos")
    op.drop_table("technical_requests")
    op.drop_table("technical_problems")
    # ### end Alembic commands ###
