"""Add post in technical requests

Revision ID: bec1c8870168
Revises: 5e9e986c0e62
Create Date: 2024-08-22 23:47:04.857638

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bec1c8870168"
down_revision: Union[str, None] = "5e9e986c0e62"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "technical_requests", sa.Column("acceptor_post_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "technical_requests", "posts", ["acceptor_post_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "technical_requests", type_="foreignkey")
    op.drop_column("technical_requests", "acceptor_post_id")
    # ### end Alembic commands ###
