"""Editing worker bid/Adding worker bid documents

Revision ID: c5b44fdd5de1
Revises: 1dc263145dc4
Create Date: 2024-05-27 14:40:55.009006

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_storages
from settings import get_settings


# revision identifiers, used by Alembic.
revision: str = "c5b44fdd5de1"
down_revision: Union[str, None] = "1dc263145dc4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "worker_bids_passports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "document",
            fastapi_storages.integrations.sqlalchemy.FileType(
                storage=get_settings().storage
            ),
            nullable=False,
        ),
        sa.Column("worker_bid_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["worker_bid_id"],
            ["worker_bids.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "worker_bids_worksheets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "document",
            fastapi_storages.integrations.sqlalchemy.FileType(
                storage=get_settings().storage
            ),
            nullable=False,
        ),
        sa.Column("worker_bid_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["worker_bid_id"],
            ["worker_bids.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "worker_work_permissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "document",
            fastapi_storages.integrations.sqlalchemy.FileType(
                storage=get_settings().storage
            ),
            nullable=False,
        ),
        sa.Column("worker_bid_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["worker_bid_id"],
            ["worker_bids.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("worker_bids", "pasport")
    op.drop_column("worker_bids", "work_permission_document")
    op.drop_column("worker_bids", "worksheet")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "worker_bids",
        sa.Column("worksheet", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "worker_bids",
        sa.Column(
            "work_permission_document",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "worker_bids",
        sa.Column("pasport", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_table("worker_work_permissions")
    op.drop_table("worker_bids_worksheets")
    op.drop_table("worker_bids_passports")
    # ### end Alembic commands ###
