"""Adding department to worker bid

Revision ID: d612fccc6fa2
Revises: c5b44fdd5de1
Create Date: 2024-05-28 13:49:43.886653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd612fccc6fa2'
down_revision: Union[str, None] = 'c5b44fdd5de1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker_bids', sa.Column('department_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'worker_bids', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'worker_bids', type_='foreignkey')
    op.drop_column('worker_bids', 'department_id')
    # ### end Alembic commands ###
