"""Add column in table material values

Revision ID: 126cbefe665d
Revises: 92b06114c96e
Create Date: 2024-10-08 16:06:28.650014

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "126cbefe665d"
down_revision: Union[str, None] = "92b06114c96e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "material_values", sa.Column("return_date", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("material_values", "return_date")
    # ### end Alembic commands ###
