"""Adding fields to expenditure and budget

Revision ID: 24d76b2255c2
Revises: 16c0d76094d9
Create Date: 2024-07-25 12:17:55.798730

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "24d76b2255c2"
down_revision: Union[str, None] = "16c0d76094d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "budget_records", sa.Column("department_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "budget_records", sa.Column("last_update", sa.DateTime(), nullable=True)
    )
    op.alter_column(
        "budget_records",
        "limit",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.create_foreign_key(
        None, "budget_records", "departments", ["department_id"], ["id"]
    )
    op.add_column("expenditures", sa.Column("creator_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "expenditures", "workers", ["creator_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "expenditures", type_="foreignkey")
    op.drop_column("expenditures", "creator_id")
    op.drop_constraint(None, "budget_records", type_="foreignkey")
    op.alter_column(
        "budget_records",
        "limit",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.drop_column("budget_records", "last_update")
    op.drop_column("budget_records", "department_id")
    # ### end Alembic commands ###
