"""Adding password to worker

Revision ID: 477080eff7f9
Revises: 24d76b2255c2
Create Date: 2024-07-25 14:38:02.301411

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "477080eff7f9"
down_revision: Union[str, None] = "24d76b2255c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workers", sa.Column("password", sa.String(), nullable=True))
    op.add_column("workers", sa.Column("can_use_crm", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workers", "can_use_crm")
    op.drop_column("workers", "password")
    # ### end Alembic commands ###
