"""Add iiko columns to departments

Revision ID: 7bc3c9953c5a
Revises: ca6a57580faf
Create Date: 2024-05-23 11:53:36.086726

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "7bc3c9953c5a"
down_revision: Union[str, None] = "ca6a57580faf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("departments", sa.Column("uuid", sa.Uuid(), nullable=True))
    op.add_column("departments", sa.Column("inn", sa.String(), nullable=True))
    op.add_column("departments", sa.Column("code", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("departments", "code")
    op.drop_column("departments", "inn")
    op.drop_column("departments", "uuid")
    # ### end Alembic commands ###
