"""Added columns for mobile

Revision ID: 82e687e944ee
Revises: 0a5d4c0b1280
Create Date: 2024-08-03 11:50:23.169691

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "82e687e944ee"
down_revision: Union[str, None] = "0a5d4c0b1280"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("departments", sa.Column("dm_id", sa.Uuid(), nullable=True))
    op.add_column(
        "departments", sa.Column("person_max_orders", sa.Integer(), nullable=True)
    )
    op.add_column(
        "departments",
        sa.Column("max_close_order_distance", sa.Integer(), nullable=True),
    )
    op.add_column(
        "departments", sa.Column("orders_collect_time", sa.Integer(), nullable=True)
    )
    op.add_column("workers", sa.Column("dm_id", sa.Uuid(), nullable=True))
    op.add_column("workers", sa.Column("dm_device_id", sa.String(), nullable=True))
    op.add_column("workers", sa.Column("dm_add_info", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workers", "dm_add_info")
    op.drop_column("workers", "dm_device_id")
    op.drop_column("workers", "dm_id")
    op.drop_column("departments", "orders_collect_time")
    op.drop_column("departments", "max_close_order_distance")
    op.drop_column("departments", "person_max_orders")
    op.drop_column("departments", "dm_id")
    # ### end Alembic commands ###
