"""Add kru access tech accountant scopes

Revision ID: 8fc6bee5eb47
Revises: e94820119bb7
Create Date: 2024-09-26 17:09:57.775679

"""

from typing import Sequence, Union

import alembic_custom.enum as c_enum

old_options = (
    "admin",
    "crm_bid",
    "crm_budget",
    "crm_expenditure",
    "crm_fac_bid",
    "crm_cc_bid",
    "crm_cc_supervisor_bid",
    "bot_bid_create",
    "bot_bid_kru",
    "bot_bid_owner",
    "bot_bid_teller_cash",
    "bot_bid_teller_card",
    "bot_bid_accountant_cash",
    "bot_bid_accountant_card",
    "bot_rate",
    "bot_worker_bid",
    "bot_technical_request_worker",
    "bot_technical_request_repairman",
    "bot_technical_request_chief_technician",
    "bot_technical_request_territorial_manager",
    "bot_technical_request_department_director",
    "bot_bid_it_worker",
    "bot_bid_it_repairman",
    "bot_bid_it_tm",
    "bot_dismissal",
)
new_options = sorted(
    old_options
    + (
        "bot_dismissal_kru",
        "bot_dismissal_accountant",
        "bot_dismissal_access",
        "bot_dismissal_tech",
    )
)

table_columns = {"post_scopes": ["scope"]}

# revision identifiers, used by Alembic.
revision: str = "8fc6bee5eb47"
down_revision: Union[str, None] = "e94820119bb7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    c_enum.update_enum(old_options, new_options, "fujiscope", table_columns)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    c_enum.update_enum(new_options, old_options, "fujiscope", table_columns)
    # ### end Alembic commands ###
