"""Add paying_comment in bids

Revision ID: a65c0aec8dfb
Revises: f921aa0af420
Create Date: 2024-10-26 19:48:09.134938

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a65c0aec8dfb"
down_revision: Union[str, None] = "f921aa0af420"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bids", sa.Column("paying_comment", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bids", "paying_comment")
    # ### end Alembic commands ###
