"""Add field department_issue_id in bids table

Revision ID: cd7283ceed69
Revises: f963192e4698
Create Date: 2024-10-18 20:16:55.637355

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cd7283ceed69"
down_revision: Union[str, None] = "f963192e4698"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bids", sa.Column("department_issue_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "department_issue_id", "bids", "departments", ["department_issue_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("department_issue_id", "bids", type_="foreignkey")
    op.drop_column("bids", "department_issue_id")
    # ### end Alembic commands ###
