"""Adding salary to work_times

Revision ID: d935c7d7fc20
Revises: f4080e95433c
Create Date: 2024-06-11 16:58:02.723901

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d935c7d7fc20"
down_revision: Union[str, None] = "f4080e95433c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("work_times", sa.Column("salary", sa.Integer(), nullable=True))
    op.drop_constraint(
        "worker_bids_passports_worker_bid_id_fkey",
        "worker_bids_passports",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "worker_bids_passports", "worker_bids", ["worker_bid_id"], ["id"]
    )
    op.drop_constraint(
        "worker_bids_worksheets_worker_bid_id_fkey",
        "worker_bids_worksheets",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "worker_bids_worksheets", "worker_bids", ["worker_bid_id"], ["id"]
    )
    op.drop_constraint(
        "worker_work_permissions_worker_bid_id_fkey",
        "worker_work_permissions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "worker_work_permissions", "worker_bids", ["worker_bid_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "worker_work_permissions", type_="foreignkey")
    op.create_foreign_key(
        "worker_work_permissions_worker_bid_id_fkey",
        "worker_work_permissions",
        "worker_bids",
        ["worker_bid_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "worker_bids_worksheets", type_="foreignkey")
    op.create_foreign_key(
        "worker_bids_worksheets_worker_bid_id_fkey",
        "worker_bids_worksheets",
        "worker_bids",
        ["worker_bid_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "worker_bids_passports", type_="foreignkey")
    op.create_foreign_key(
        "worker_bids_passports_worker_bid_id_fkey",
        "worker_bids_passports",
        "worker_bids",
        ["worker_bid_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("work_times", "salary")
    # ### end Alembic commands ###
