"""Add dismissal

Revision ID: ed9bca4a9243
Revises: 8fc6bee5eb47
Create Date: 2024-09-27 16:13:36.548088

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM
import fastapi_storages

from settings import get_settings

# revision identifiers, used by Alembic.
revision: str = "ed9bca4a9243"
down_revision: Union[str, None] = "8fc6bee5eb47"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dismissals",
        sa.Column("worker_id", sa.Integer(), nullable=False),
        sa.Column(
            "tech_state",
            ENUM(
                "pending",
                "approved",
                "denied",
                "pending_approval",
                "skipped",
                "not_relevant",
                name="approvalstatus",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "accountant_state",
            ENUM(
                "pending",
                "approved",
                "denied",
                "pending_approval",
                "skipped",
                "not_relevant",
                name="approvalstatus",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "access_state",
            ENUM(
                "pending",
                "approved",
                "denied",
                "pending_approval",
                "skipped",
                "not_relevant",
                name="approvalstatus",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "kru_state",
            ENUM(
                "pending",
                "approved",
                "denied",
                "pending_approval",
                "skipped",
                "not_relevant",
                name="approvalstatus",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("tech_comment", sa.String(), nullable=True),
        sa.Column("accountant_comment", sa.String(), nullable=True),
        sa.Column("access_comment", sa.String(), nullable=True),
        sa.Column("kru_comment", sa.String(), nullable=True),
        sa.Column("create_date", sa.DateTime(), nullable=False),
        sa.Column("close_date", sa.DateTime(), nullable=True),
        sa.Column("kru_approval_date", sa.DateTime(), nullable=True),
        sa.Column("accountant_approval_date", sa.DateTime(), nullable=True),
        sa.Column("access_approval_date", sa.DateTime(), nullable=True),
        sa.Column("tech_approval_date", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["worker_id"],
            ["workers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dismissal_documents",
        sa.Column(
            "document",
            fastapi_storages.integrations.sqlalchemy.FileType(
                storage=get_settings().storage
            ),
            nullable=False,
        ),
        sa.Column("dismissal_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dismissal_id"],
            ["dismissals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dismissal_documents")
    op.drop_table("dismissals")
    # ### end Alembic commands ###
