"""Add field department_issue_id in bids table

Revision ID: f921aa0af420
Revises: f963192e4698
Create Date: 2024-10-21 08:20:59.511477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f921aa0af420'
down_revision: Union[str, None] = 'f963192e4698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bids', sa.Column('paying_department_id', sa.Integer(), nullable=True))
    op.create_foreign_key('paying_department_id', 'bids', 'departments', ['paying_department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('paying_department_id', 'bids', type_='foreignkey')
    op.drop_column('bids', 'paying_department_id')
    # ### end Alembic commands ###
