name: build-test-deploy
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          path: src/frontend
      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.2.x"
      - run: npm install
      - name: build frontend
        run: npm run build
