name: build-test-deploy
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.2.x"
      - name: npm install
        working-directory: ./src/frontend
        run: npm install
      - name: build frontend
        working-directory: ./src/frontend
        run: npm run build
