name: lint-check
on: push
jobs:
  build-crm:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.2.x"
      - name: npm install
        working-directory: ./sevices/crm
        run: npm install
      - name: build frontend
        working-directory: ./sevices/crm
        run: npm run build
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        working-directory: ./services/backend
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt
          pip install --no-cache-dir ruff
      - name: Run Ruff
        working-directory: ./sevices/backend
        run: |
          ruff check .
          ruff format --check .
