name: lint-check
on: push
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.2.x"
      - name: npm install
        working-directory: ./src/frontend
        run: npm install
      - name: build frontend
        working-directory: ./src/frontend
        run: npm run build
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        working-directory: ./src/backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff
      # Update output format to enable automatic inline annotations.
      - name: Run Ruff
        working-directory: ./src/backend
        run: ruff check --output-format=github .
